name: rss_reader_cupertino
description: A Cupertino-style RSS reader for Android built with Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  html: ^0.15.5
  http: ^1.2.2
  shared_preferences: ^2.3.2
  webfeed_plus: ^1.1.2
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
